### ISSUE TITLE
Step 3 confusion with "it"

### ISSUE THREAD

**Issue by Knatan** [Shinigati/LoHUndubVita#1]
As of revision 6 of the guide, in step 3 you write:
>First open up vitashell and navigate to ux0:patch/ you will also need to know the titleid of your game but for me it was PCSB00866 (AUS/EUR) if there is already a patch folder present for your game just rename it for now

I am unsure if that you mean when you say "it".
For example, I have these folders:
ux0:patch/PCSE00777/patch/

Do you want me to rename it like this: ux0:patch/PCSE00777/renamed/ ?
Or do you want me to rename it like this: ux0:patch/renamed/patch/ ?

I just like to make sure so I don't destroy my Vita in the guessing process.

**Comment by Shinigati** [comment]
You should already have at least a few games un ux0:patch so it shouldn't be difficult to figure out but it needs to be renamed like this: ux0:patch/TITLEID-HERE-RENAME-ME/
